app = "cookai_api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  headers = { "User-Agent" = "fly-health-check" }

[machine]
  memory = "512mb"  # Aumentado para evitar OOM
  cpu_kind = "shared"
  cpus = 1

